name: Deploy to Staging (dev.shigenoki.com)

on:
  push:
    branches: [ "main" ]

# リポジトリ設定側（Settings → Actions → General）でも
# 「Workflow permissions: Read and write」を必ず有効に。
permissions:
  contents: read
  packages: write

# 画像名を常に小文字化してタグ生成
env:
  IMAGE: ghcr.io/${{ toLower(github.repository) }}

concurrency:
  group: staging-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}          # ← 文字列 'actor' ではなく式
          password: ${{ secrets.GITHUB_TOKEN }}  # ← GITHUB_TOKEN でOK（上の permissions が必要）

      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE }}:main
            ${{ env.IMAGE }}:${{ github.sha }}
          provenance: false

      - name: Pull & Restart via Compose
        run: |
          cd /srv/dev
          docker compose pull app
          docker compose up -d
          docker image prune -f
