name: Deploy to Staging (dev.shigenoki.com)

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

concurrency:
  group: staging-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      # 画像名（常に小文字）
      - name: Compute lowercase image name
        run: echo "IMAGE=ghcr.io/${GITHUB_REPOSITORY,,}" >> "$GITHUB_ENV"

      # （必要なら）最初だけ busybox で :main を作るブートストラップ
      # パッケージが完全に空なら有効化すると楽です。普段は省略OK。
      # - name: Bootstrap :main tag (optional)
      #   run: |
      #     set -eux
      #     docker pull busybox:latest
      #     docker tag busybox:latest "${IMAGE}:main"
      #     docker push "${IMAGE}:main"

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push image (:main and :sha)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE }}:main
            ${{ env.IMAGE }}:${{ github.sha }}
          provenance: false

      # ← ここで “本当にあるか” を検証。無ければこの時点で止める（原因がログに出る）
      - name: Verify tags exist on GHCR
        run: |
          set -eux
          docker buildx imagetools inspect "${IMAGE}:${GITHUB_SHA}" >/dev/null
          docker buildx imagetools inspect "${IMAGE}:main" >/dev/null || echo "::warning ::':main' is missing (deploy will use :sha)"

      # ここが肝：サーバの compose を “今回の :sha を指す override” で確実にデプロイ
      - name: Deploy with SHA pin (compose override)
        run: |
          set -eux
          cd /srv/dev
          cat > docker-compose.override.yml <<EOF
          services:
            app:
              image: ${IMAGE}:${GITHUB_SHA}
          EOF
          docker compose pull app
          docker compose up -d --no-deps app
          docker image prune -f

      # 必要なら最後に :main を使う運用へ戻す（今はコメントアウト推奨）
      # - name: Remove override (back to :main)
      #   if: always()
      #   run: |
      #     rm -f /srv/dev/docker-compose.override.yml || true
